### ISSUE TITLE
Errors during pip install of pickle5 in python 3.8 virtual environment

### ISSUE THREAD

**Issue by ThomIves** [pitrou/pickle5-backport#12]
While attempting to 'pip install pickle5' on a windows 10 machine inside a python 3.8 virtual environment, I received the terminal output shown in the attached file. 

[Pip_install_pickle5_Errors_terminal_output.txt](https://github.com/pitrou/pickle5-backport/files/3827742/Pip_install_pickle5_Errors_terminal_output.txt)

**Comment by pitrou** [comment]
Sorry for the delay. But as mentioned in the README and on PyPI, "it should work with Python 3.5, 3.6 and 3.7". The `pickle5` package is basically useless on Python 3.8, where the backported functionality is standard.

**Comment by ThomIves** [comment]
> Sorry for the delay. But as mentioned in the README and on PyPI, "it should work with Python 3.5, 3.6 and 3.7". The `pickle5` package is basically useless on Python 3.8, where the backported functionality is standard.

Ah! Sorry for not reading more carefully.

**Comment by raghuhp92** [comment]
Hi..Im a beginner in python.. I need a clarification. So as per above comments if we couldn't use Pickle5 in Python 3.8, then what is an alternative. is there any other method to load a pickle file in python 3.8....Few codes were not working even if i use usual pickle instead of pickle5 to load a pkl format file in python3.8.

Im getting below error while loading the SARIMAX model pkl file while i created.

KeyError                                  Traceback (most recent call last)
<ipython-input-8-be37530ed5e9> in <module>
      1 import pickle as pickle
      2 from pickle import load
----> 3 loaded_model = load(open(path, 'rb'))

statsmodels\tsa\statespace\_representation.pyx in statsmodels.tsa.statespace._representation.dStatespace.__setstate__()

KeyError: 'initial_diffuse_state_cov'


Is this problem occurs because of pkl file loading error or problem with the SARIMAX model. Can anyone please help me in this??
Thanks
