### ISSUE TITLE
Pickling memoryviews

### ISSUE THREAD

**Issue by jakirkham** [pitrou/pickle5-backport#4]
Would it make sense to consider pickling `memoryview`s here as well or is that too far out of scope?

**Comment by jakirkham** [comment]
To clarify my suggestion a bit, it would be nice if this...

```python
pickle.dumps(memoryview(a), protocol=5)
```

...was converted to this

```python
pickle.dumps(pickle.PickleBuffer(memoryview(a)), protocol=5)
```

**Comment by pitrou** [comment]
Sorry for not seeing this issue before. `pickle5` does not aim to change the standard set of picklable types. In other words, `memoryview` will stay unpicklable per se (because there are no "obviously right" semantics). Third-party tools like `cloudpickle` can still choose to override that decision ;-)
